/**
 * Graph entry wizard (P0-4): generate a `.graphloupe/entry.py` adapter that points at a
 * user-specified symbol. Pure (no vscode/node) so it's unit-tested in entryWizard.test.ts;
 * extension.ts drives the file/symbol pickers and writes the file.
 */

/** The graph entry the wizard writes to graphloupe.graphEntry. `entry` is the adapter
 *  module (`.graphloupe/entry.py`, put on sys.path by the worker). */
export const ADAPTER_ENTRY = "entry:build_graph";

/**
 * Adapter source pointing at `<module>:<symbol>`. build_graph() calls the target when it's
 * a factory (callable) and returns it directly when it's an already-compiled graph exposed
 * as a module variable — so both shapes load through the frozen `module:callable` contract.
 */
export function renderAdapter(module: string, symbol: string): string {
  return `# Auto-generated by GraphLoupe (P0-4 entry wizard) — points at your graph.
# Safe to delete or regenerate via "GraphLoupe: Select Graph".
from ${module} import ${symbol} as _target


def build_graph():
    # factory -> call it; already-compiled graph (a module variable) -> return as-is
    return _target() if callable(_target) else _target
`;
}
